apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uploader-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-first-approach/Evolution.Uploader.git
    targetRevision: HEAD
    path: argo/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false