---
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: mymesh
metadata:
  name: mymesh-gateway
  namespace: uploader
spec:
  conf:
    listeners:
    - port: 80
      protocol: HTTP
  selectors:
  - match:
      kuma.io/service: mymesh-gateway_gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: mymesh
metadata:
  name: mymesh-gateway-route
  namespace: uploader
spec:
  conf:
   http:
    rules:
    - matches:
      - path:
          match: PREFIX
          value: /uploads/test
      backends:
      - destination:
          kuma.io/service: uploader-api_uploader_svc_80
        weight: 1
  selectors:
  - match:
      kuma.io/service: mymesh-gateway_gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: mymesh-gateway-instance
  namespace: uploader
spec:
  replicas: 1
  serviceType: ClusterIP
  tags:
    kuma.io/service: mymesh-gateway_gateway