apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: kubeos-baseline
  description: A collection of all kubeos cluster base line.
spec:
  targets:
    - ./catalog-info.yaml
    - ./addons/base/flagger/catalog-info.yaml
    - ./addons/base/prometheus-stack/catalog-info.yaml