apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  volumes:
    - name: buzy-store
  containers:
  - image: busybox
    # command:
    #   - sleep
    #   - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      limits:
        memory: "200Mi"
        cpu: "0.2"    
  restartPolicy: Always

