apiVersion: v1
kind: Pod
metadata:
  name: mycurlpod
  labels:
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: mymesh
  annotations:
    kuma.io/mesh: mymesh
spec:
  containers:
  - name: mycurlcontainer
    image: curlimages/curl
    command: ['sleep', '3600']
