apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flagger-loadtester-monitor
  namespace: monitoring
  labels:
    metricScraper: prometheus
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /metrics
  selector:
    matchLabels:
      metricScraper: prometheus