apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flagger-loadtester-monitor
  namespace:  flagger-system
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /metrics
  namespaceSelector:
    any: 'true'
  selector:
    matchLabels:
      metricScraper: prometheus