apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# generators:
#   - "redis-chart.yaml"
helmCharts:
- name: redis
  includeCRDs: false
  valuesInline:
    redis:
      usePassword: false
  releaseName: bitnami/redis
  repo: https://charts.bitnami.com/bitnami