apiVersion: kuma.io/v1alpha1
kind: RateLimit 
mesh: mymesh 
metadata:
  name: rate-limit-all-to-backend
spec:
  sources:
    - match:
        kuma.io/service: "*"
  destinations:
    - match:
        kuma.io/service: uploader-api_uploader_svc_80
  conf:
    http:
      requests: 2
      interval: 10s
      onRateLimit:
        status: 423
        headers:
          - key: "x-kuma-rate-limited"
            value: "true"
            append: true
         