apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus-stack
  description: Complete list of all prometheus relates stack, exporters, agents, grafana dashboards.
  annotations:
    backstage.io/kubernetes-id: prometheus-stack
    github.com/project-slug: kubeosx/kubeos-baseline
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: monitoring
    prometheus.io/alert: all
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
spec:
  type: service
  owner: infrastructure
  lifecycle: experimental
