apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus-stack
  description: Complete list of all prometheus relates stack, exporters, agents, grafana dashboards.
  annotations:
    backstage.io/kubernetes-id: prometheus-stack
    github.com/project-slug: kubeosx/kubeos-baseline
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: monitoring
    prometheus.io/alert: all
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
  tags:
    - node-exporter
    - prometheus
    - grafana
  links:
    - url: https://grafana.com/docs/grafana/latest/?pg=oss-graf&plcmt=hero-btn-2
      title: Learn Grafana
      icon: web
    - url: https://prometheus.io/docs/introduction/overview/
      title: Learn Prometheus
      icon: web
    - url: https://github.com/prometheus-operator/kube-prometheus/issues
      title: Support/Issues
      icon: help
    - url: https://github.com/prometheus-operator/kube-prometheus
      title: Github
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  owner: platform-engineering-team
  lifecycle: experimental
  subcomponentOf: kubeos-baseline
  system: kubeos-idp